### ISSUE TITLE
gulp-sourcemaps support

### ISSUE THREAD

**Issue by demisx** [sindresorhus/gulp-myth#7]
It appears that this plug-in does not support sourcemap generation via `gulp-sourcemaps` plugin https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support. I think would be beneficial from consistency point of view if it did. What are your thoughts on that?

**Comment by kevva** [comment]
Should we keep the `sourcemap` option?

**Comment by sindresorhus** [comment]
No

**Comment by kevva** [comment]
https://github.com/segmentio/myth/issues/116

**Comment by kevva** [comment]
When setting `sourcemapAsObject: true` which is needed for `vinyl-sourcemaps-apply` it just throws `Uncaught /home/kevva/Projects/gulp-myth/fixture/fixture.css:1:1: Unclosed block`. Suspect this is coming from `autoprefixer`,

**Comment by kevva** [comment]
I've tried using `myth` as a `rework` plugin instead and while I get the sourcemap object back it's still incorrect. It's missing the `file` property and the `sources` is incorrect (only includes the default name `source.css`).

**Comment by sindresorhus** [comment]
:arrow_up: As per suggested here: https://github.com/segmentio/myth/issues/116

**Comment by sindresorhus** [comment]
Closing as this project is deprecated.
